<?php
$theme = array (
  'attributes' => 
  array (
    'highlight' => '#eeeeee',
    'select' => '#cccccc',
    'ol_menucolor' => '#ffffff',
    'ol_wincolor' => '#eeeee0',
    'ol_background' => '#677EB1',
    'recordlist_orientation' => 'left',
    'recordlist_vorientation' => 'top',
    'recordlist_icons' => true,
    'dialog_theme_name' => 'alphacube',
    'dialog_theme_load' => true,
    'basepath' => 'atk/themes/t3skin/',
    'customtpls' => 'scan templates/',
    'graphBgColor' => '#eeeeee',
    'compatible_menus' => 
    array (
      0 => 'achievo',
    ),
  ),
  'files' => 
  array (
    'icons' => 
    array (
      'lock' => 
      array (
        'lock_exclusive.gif' => 'atk/themes/default/icons/lock/lock_exclusive.gif',
        'lock_exclusive_head.gif' => 'atk/themes/default/icons/lock/lock_exclusive_head.gif',
        'lock_shared.gif' => 'atk/themes/default/icons/lock/lock_shared.gif',
        'lock_shared_head.gif' => 'atk/themes/default/icons/lock/lock_shared_head.gif',
      ),
      'recordlist' => 
      array (
        'canceled.gif' => 'atk/themes/default/icons/recordlist/canceled.gif',
        'copy.gif' => 'atk/themes/t3skin/icons/recordlist/copy.gif',
        'default.gif' => 'atk/themes/default/icons/recordlist/default.gif',
        'delete.gif' => 'atk/themes/t3skin/icons/recordlist/delete.gif',
        'document.gif' => 'atk/themes/default/icons/recordlist/document.gif',
        'done.gif' => 'atk/themes/default/icons/recordlist/done.gif',
        'edit.gif' => 'atk/themes/t3skin/icons/recordlist/edit.gif',
        'export.gif' => 'atk/themes/default/icons/recordlist/export.gif',
        'preview.gif' => 'atk/themes/default/icons/recordlist/preview.gif',
        'select.gif' => 'atk/themes/default/icons/recordlist/select.gif',
        'view.gif' => 'atk/themes/t3skin/icons/recordlist/view.gif',
      ),
      'toolbar' => 
      array (
        'bold.gif' => 'atk/themes/default/icons/toolbar/bold.gif',
        'delimiter.gif' => 'atk/themes/default/icons/toolbar/delimiter.gif',
        'italic.gif' => 'atk/themes/default/icons/toolbar/italic.gif',
        'link.gif' => 'atk/themes/default/icons/toolbar/link.gif',
        'underline.gif' => 'atk/themes/default/icons/toolbar/underline.gif',
      ),
      'tree' => 
      array (
        'tree_collapse.gif' => 'atk/themes/default/icons/tree/tree_collapse.gif',
        'tree_end.gif' => 'atk/themes/default/icons/tree/tree_end.gif',
        'tree_end_minus.gif' => 'atk/themes/default/icons/tree/tree_end_minus.gif',
        'tree_end_plus.gif' => 'atk/themes/default/icons/tree/tree_end_plus.gif',
        'tree_expand.gif' => 'atk/themes/default/icons/tree/tree_expand.gif',
        'tree_extfile.gif' => 'atk/themes/default/icons/tree/tree_extfile.gif',
        'tree_leaf.gif' => 'atk/themes/default/icons/tree/tree_leaf.gif',
        'tree_space.gif' => 'atk/themes/default/icons/tree/tree_space.gif',
        'tree_split.gif' => 'atk/themes/default/icons/tree/tree_split.gif',
        'tree_split_minus.gif' => 'atk/themes/default/icons/tree/tree_split_minus.gif',
        'tree_split_plus.gif' => 'atk/themes/default/icons/tree/tree_split_plus.gif',
        'tree_vertline.gif' => 'atk/themes/default/icons/tree/tree_vertline.gif',
      ),
    ),
    'images' => 
    array (
      'arrow.gif' => 'atk/themes/default/images/arrow.gif',
      'arrowdown.gif' => 'atk/themes/default/images/arrowdown.gif',
      'arrowup.gif' => 'atk/themes/default/images/arrowup.gif',
      'blank.gif' => 'atk/themes/default/images/blank.gif',
      'empty.gif' => 'atk/themes/default/images/empty.gif',
      'help.gif' => 'atk/themes/default/images/help.gif',
      'required_field.gif' => 'atk/themes/default/images/required_field.gif',
    ),
    'styles' => 
    array (
      'atkdateattribute.css' => 'atk/themes/default/styles/atkdateattribute.css',
      'atkdebug.css' => 'atk/themes/default/styles/atkdebug.css',
      'atkdropdownmenu.css' => 'atk/themes/default/styles/atkdropdownmenu.css',
      'atkmanytomanyselectrelation.css' => 'atk/themes/default/styles/atkmanytomanyselectrelation.css',
      'atkmanytoonerelation.css' => 'atk/themes/default/styles/atkmanytoonerelation.css',
      'cookmenu.css' => 'atk/themes/default/styles/cookmenu.css',
      'debugger.css' => 'atk/themes/default/styles/debugger.css',
      'dhtmlmenu.css' => 'atk/themes/default/styles/dhtmlmenu.css',
      'fck_mcpuk_browser.css' => 'atk/themes/default/styles/fck_mcpuk_browser.css',
      'menu.css' => 'atk/themes/default/styles/menu.css',
      'recordlist.css' => 'atk/themes/t3skin/styles/recordlist.css',
      'sections.css' => 'atk/themes/default/styles/sections.css',
      'style.css' => 'atk/themes/t3skin/styles/style.css',
      'tabs.css' => 'atk/themes/default/styles/tabs.css',
    ),
    'templates' => 
    array (
      'action.tpl' => 'atk/themes/default/templates/action.tpl',
      'actionpage.tpl' => 'atk/themes/default/templates/actionpage.tpl',
      'box.tpl' => 'atk/themes/t3skin/templates/box.tpl',
      'datagrid.tpl' => 'atk/themes/default/templates/datagrid.tpl',
      'dgindex.tpl' => 'atk/themes/default/templates/dgindex.tpl',
      'dglimit.tpl' => 'atk/themes/default/templates/dglimit.tpl',
      'dgpaginator.tpl' => 'atk/themes/default/templates/dgpaginator.tpl',
      'dhtml_menu.tpl' => 'atk/themes/default/templates/dhtml_menu.tpl',
      'dialog.tpl' => 'atk/themes/default/templates/dialog.tpl',
      'editform.tpl' => 'atk/themes/default/templates/editform.tpl',
      'extendableshuttle.tpl' => 'atk/themes/default/templates/extendableshuttle.tpl',
      'field.tpl' => 'atk/themes/default/templates/field.tpl',
      'integratededitform.tpl' => 'atk/themes/default/templates/integratededitform.tpl',
      'list.tpl' => 'atk/themes/default/templates/list.tpl',
      'lockinfo.tpl' => 'atk/themes/default/templates/lockinfo.tpl',
      'login.tpl' => 'atk/themes/default/templates/login.tpl',
      'panetabs.tpl' => 'atk/themes/default/templates/panetabs.tpl',
      'recordlist.tpl' => 'atk/themes/default/templates/recordlist.tpl',
      'searchform.tpl' => 'atk/themes/default/templates/searchform.tpl',
      'smartcriterium.tpl' => 'atk/themes/default/templates/smartcriterium.tpl',
      'smartsearchform.tpl' => 'atk/themes/default/templates/smartsearchform.tpl',
      'statusbar.tpl' => 'atk/themes/default/templates/statusbar.tpl',
      'tabbededitform.tpl' => 'atk/themes/default/templates/tabbededitform.tpl',
      'tabs.tpl' => 'atk/themes/default/templates/tabs.tpl',
      'viewform.tpl' => 'atk/themes/default/templates/viewform.tpl',
      'body.tpl' => 'themes/default/templates/body.tpl',
      'body_pda.tpl' => 'themes/default/templates/body_pda.tpl',
      'contentwithlegend.tpl' => 'themes/default/templates/contentwithlegend.tpl',
      'crm_lastviewed.tpl' => 'themes/default/templates/crm_lastviewed.tpl',
      'horizontal.tpl' => 'themes/default/templates/horizontal.tpl',
      'hours_adminfooter.tpl' => 'themes/default/templates/hours_adminfooter.tpl',
      'hours_adminheader.tpl' => 'themes/default/templates/hours_adminheader.tpl',
      'hours_adminheader_weekview.tpl' => 'themes/default/templates/hours_adminheader_weekview.tpl',
      'hoursurvey_footer.tpl' => 'themes/default/templates/hoursurvey_footer.tpl',
      'hoursurvey_header.tpl' => 'themes/default/templates/hoursurvey_header.tpl',
      'index.tpl' => 'themes/default/templates/index.tpl',
      'simplesearch.tpl' => 'themes/default/templates/simplesearch.tpl',
      'vertical.tpl' => 'themes/default/templates/vertical.tpl',
      'menu.tpl' => 'atk/themes/t3skin/templates/menu.tpl',
    ),
  ),
  'modulefiles' => 
  array (
    'scheduler' => 
    array (
      'icons' => 
      array (
        'recordlist' => 
        array (
          'accept.gif' => 'default/icons/recordlist/accept.gif',
          'reject.gif' => 'default/icons/recordlist/reject.gif',
        ),
      ),
      'images' => 
      array (
        'add.gif' => 'default/images/add.gif',
        'alarm.gif' => 'default/images/alarm.gif',
        'arrow_left.gif' => 'default/images/arrow_left.gif',
        'arrow_right.gif' => 'default/images/arrow_right.gif',
        'attendee.gif' => 'default/images/attendee.gif',
        'attendees.gif' => 'default/images/attendees.gif',
        'cake.gif' => 'default/images/cake.gif',
        'category.gif' => 'default/images/category.gif',
        'ne.gif' => 'default/images/ne.gif',
        'ne2.gif' => 'default/images/ne2.gif',
        'note.gif' => 'default/images/note.gif',
        'ny.gif' => 'default/images/ny.gif',
        'ny2.gif' => 'default/images/ny2.gif',
        'private.gif' => 'default/images/private.gif',
        'recurring.gif' => 'default/images/recurring.gif',
        'todo.gif' => 'default/images/todo.gif',
      ),
    ),
    'todo' => 
    array (
      'icons' => 
      array (
        'recordlist' => 
        array (
          'complete.gif' => 'default/icons/recordlist/complete.gif',
        ),
      ),
    ),
    'quotation' => 
    array (
      'icons' => 
      array (
        'recordlist' => 
        array (
          'set_accepted.gif' => 'default/icons/recordlist/set_accepted.gif',
          'set_billed.gif' => 'default/icons/recordlist/set_billed.gif',
          'set_called.gif' => 'default/icons/recordlist/set_called.gif',
          'set_completed.gif' => 'default/icons/recordlist/set_completed.gif',
          'set_prepaid.gif' => 'default/icons/recordlist/set_prepaid.gif',
          'set_rejected.gif' => 'default/icons/recordlist/set_rejected.gif',
          'set_sent.gif' => 'default/icons/recordlist/set_sent.gif',
        ),
      ),
    ),
  ),
)
?>